"""empty message

Revision ID: 0e32505c4f1f
Revises: 12504233aeb0
Create Date: 2023-01-26 19:54:50.767118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e32505c4f1f'
down_revision = '12504233aeb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direcciones_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('documentos_direccions_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'direcciones', ['direcciones_id'], ['id'])
        batch_op.drop_column('direccions_id')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direcciones_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('pedidos_direccions_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'direcciones', ['direcciones_id'], ['id'])
        batch_op.drop_column('direccions_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccions_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pedidos_direccions_id_fkey', 'direcciones', ['direccions_id'], ['id'])
        batch_op.drop_column('direcciones_id')

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccions_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('documentos_direccions_id_fkey', 'direcciones', ['direccions_id'], ['id'])
        batch_op.drop_column('direcciones_id')

    # ### end Alembic commands ###
